USE [HospitalDB]
create table MOCK_DATA (
	id INT,
	user_name VARCHAR(50),
	Email VARCHAR(50),
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	gender VARCHAR(50),
	date_of_birth DATE
);

insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (1, 'obett0', 'obett0@mlb.com', 'Osbourne', 'Bett', 'Male', '6/29/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (2, 'aprise1', 'aprise1@tumblr.com', 'Ardath', 'Prise', 'Female', '5/6/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (3, 'afranies2', 'afranies2@etsy.com', 'Alfreda', 'Franies', 'Female', '5/7/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (4, 'mvarty3', 'mvarty3@mit.edu', 'Maryann', 'Varty', 'Female', '7/25/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (5, 'rdeftie4', 'rdeftie4@blogspot.com', 'Rodrigo', 'Deftie', 'Male', '7/22/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (6, 'kwavish5', 'kwavish5@sakura.ne.jp', 'Kermit', 'Wavish', 'Male', '2/2/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (7, 'ibarczewski6', 'ibarczewski6@stanford.edu', 'Iolande', 'Barczewski', 'Female', '6/17/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (8, 'ffodden7', 'ffodden7@qq.com', 'Filmore', 'Fodden', 'Male', '7/21/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (9, 'mhaggeth8', 'mhaggeth8@twitter.com', 'Merrily', 'Haggeth', 'Female', '12/22/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (10, 'apipkin9', 'apipkin9@feedburner.com', 'Aloysius', 'Pipkin', 'Male', '1/30/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (11, 'lwilkiea', 'lwilkiea@yahoo.com', 'Liva', 'Wilkie', 'Female', '5/7/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (12, 'lsoftleyb', 'lsoftleyb@rambler.ru', 'Laughton', 'Softley', 'Male', '7/13/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (13, 'hbagnalc', 'hbagnalc@1688.com', 'Halley', 'Bagnal', 'Female', '12/27/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (14, 'rkensittd', 'rkensittd@eventbrite.com', 'Ronica', 'Kensitt', 'Female', '3/24/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (15, 'ateasee', 'ateasee@hibu.com', 'Anton', 'Tease', 'Male', '4/14/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (16, 'jellcomef', 'jellcomef@quantcast.com', 'Jeff', 'Ellcome', 'Male', '4/11/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (17, 'lmerrigansg', 'lmerrigansg@washington.edu', 'Lorant', 'Merrigans', 'Bigender', '5/1/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (18, 'espooleh', 'espooleh@sohu.com', 'Ernie', 'Spoole', 'Male', '12/17/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (19, 'dstarlingi', 'dstarlingi@marketwatch.com', 'Dominick', 'Starling', 'Male', '11/29/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (20, 'lseczykj', 'lseczykj@amazonaws.com', 'Leandra', 'Seczyk', 'Female', '2/25/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (21, 'bholthamk', 'bholthamk@weather.com', 'Blake', 'Holtham', 'Female', '12/21/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (22, 'apiwelll', 'apiwelll@vinaora.com', 'Anabal', 'Piwell', 'Female', '6/8/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (23, 'ktyerm', 'ktyerm@discuz.net', 'Kerianne', 'Tyer', 'Female', '8/13/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (24, 'xmityushkinn', 'xmityushkinn@addthis.com', 'Xena', 'Mityushkin', 'Female', '10/29/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (25, 'boneligano', 'boneligano@usda.gov', 'Bourke', 'O'' Neligan', 'Male', '1/22/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (26, 'rbaylisp', 'rbaylisp@surveymonkey.com', 'Rollins', 'Baylis', 'Male', '6/19/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (27, 'nstevensonq', 'nstevensonq@time.com', 'Nadeen', 'Stevenson', 'Female', '3/8/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (28, 'hblabier', 'hblabier@bluehost.com', 'Harold', 'Blabie', 'Genderfluid', '2/9/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (29, 'clillemans', 'clillemans@parallels.com', 'Corrie', 'Lilleman', 'Female', '10/29/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (30, 'jflintufft', 'jflintufft@feedburner.com', 'Joly', 'Flintuff', 'Female', '10/21/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (31, 'bfishpooleu', 'bfishpooleu@moonfruit.com', 'Buiron', 'Fishpoole', 'Male', '9/16/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (32, 'hwillsheev', 'hwillsheev@goo.gl', 'Harrietta', 'Willshee', 'Female', '6/3/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (33, 'ctattersfieldw', 'ctattersfieldw@creativecommons.org', 'Cherrita', 'Tattersfield', 'Female', '6/1/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (34, 'cstrutzx', 'cstrutzx@hc360.com', 'Chan', 'Strutz', 'Male', '5/8/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (35, 'mwinterfloody', 'mwinterfloody@twitter.com', 'Margo', 'Winterflood', 'Female', '1/21/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (36, 'clerez', 'clerez@discovery.com', 'Crichton', 'Lere', 'Male', '1/4/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (37, 'bpersitt10', 'bpersitt10@prweb.com', 'Bella', 'Persitt', 'Agender', '2/2/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (38, 'cmccobb11', 'cmccobb11@buzzfeed.com', 'Con', 'McCobb', 'Female', '1/30/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (39, 'mfetherstone12', 'mfetherstone12@sun.com', 'Marwin', 'Fetherstone', 'Male', '1/21/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (40, 'hjaxon13', 'hjaxon13@aol.com', 'Hedy', 'Jaxon', 'Female', '7/7/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (41, 'cpeltz14', 'cpeltz14@reddit.com', 'Carri', 'Peltz', 'Female', '1/12/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (42, 'ndoubrava15', 'ndoubrava15@t.co', 'Nikola', 'Doubrava', 'Male', '9/25/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (43, 'ajuschka16', 'ajuschka16@barnesandnoble.com', 'Adina', 'Juschka', 'Female', '10/26/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (44, 'wmcclymont17', 'wmcclymont17@arizona.edu', 'Wadsworth', 'McClymont', 'Male', '2/18/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (45, 'fflindall18', 'fflindall18@youtu.be', 'Fidelia', 'Flindall', 'Female', '5/6/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (46, 'rgiraudeau19', 'rgiraudeau19@clickbank.net', 'Rafferty', 'Giraudeau', 'Male', '11/20/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (47, 'btomala1a', 'btomala1a@seattletimes.com', 'Bettina', 'Tomala', 'Female', '12/25/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (48, 'rmac1b', 'rmac1b@youku.com', 'Randall', 'Mac', 'Male', '3/31/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (49, 'tpalley1c', 'tpalley1c@wsj.com', 'Tamarah', 'Palley', 'Female', '11/15/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (50, 'dbernardinelli1d', 'dbernardinelli1d@parallels.com', 'Dot', 'Bernardinelli', 'Non-binary', '1/24/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (51, 'dclausius1e', 'dclausius1e@ifeng.com', 'Danette', 'Clausius', 'Female', '10/7/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (52, 'loneill1f', 'loneill1f@senate.gov', 'Loraine', 'O''Neill', 'Female', '4/13/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (53, 'pcharrett1g', 'pcharrett1g@squidoo.com', 'Phillis', 'Charrett', 'Female', '6/18/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (54, 'atwede1h', 'atwede1h@shinystat.com', 'Althea', 'Twede', 'Female', '11/1/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (55, 'dharfoot1i', 'dharfoot1i@topsy.com', 'Dominick', 'Harfoot', 'Male', '4/9/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (56, 'abukowski1j', 'abukowski1j@hud.gov', 'Alexandre', 'Bukowski', 'Male', '3/9/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (57, 'jjotham1k', 'jjotham1k@blogtalkradio.com', 'Jase', 'Jotham', 'Male', '12/27/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (58, 'gteague1l', 'gteague1l@meetup.com', 'Grady', 'Teague', 'Male', '4/7/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (59, 'kduhig1m', 'kduhig1m@joomla.org', 'Karol', 'Duhig', 'Female', '10/7/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (60, 'amacintosh1n', 'amacintosh1n@hexun.com', 'Avigdor', 'MacIntosh', 'Male', '5/24/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (61, 'mgyford1o', 'mgyford1o@uol.com.br', 'Morganica', 'Gyford', 'Female', '8/15/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (62, 'dmckain1p', 'dmckain1p@geocities.jp', 'Davide', 'McKain', 'Male', '7/5/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (63, 'lnewitt1q', 'lnewitt1q@nyu.edu', 'Linus', 'Newitt', 'Male', '10/28/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (64, 'lbeyn1r', 'lbeyn1r@wsj.com', 'Lilla', 'Beyn', 'Female', '9/3/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (65, 'mrentz1s', 'mrentz1s@who.int', 'Morty', 'Rentz', 'Male', '7/16/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (66, 'cmound1t', 'cmound1t@chron.com', 'Carlye', 'Mound', 'Female', '6/21/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (67, 'mmichie1u', 'mmichie1u@youtube.com', 'Matthieu', 'Michie', 'Male', '11/29/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (68, 'brammell1v', 'brammell1v@typepad.com', 'Barthel', 'Rammell', 'Male', '12/16/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (69, 'ahaslam1w', 'ahaslam1w@is.gd', 'Anitra', 'Haslam', 'Female', '7/17/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (70, 'jglayzer1x', 'jglayzer1x@privacy.gov.au', 'Janette', 'Glayzer', 'Female', '6/6/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (71, 'csurmeyer1y', 'csurmeyer1y@tumblr.com', 'Caitrin', 'Surmeyer', 'Female', '5/9/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (72, 'btansey1z', 'btansey1z@scribd.com', 'Broderick', 'Tansey', 'Agender', '5/20/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (73, 'cstainson20', 'cstainson20@nsw.gov.au', 'Carrol', 'Stainson', 'Non-binary', '9/11/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (74, 'zolesen21', 'zolesen21@howstuffworks.com', 'Zia', 'Olesen', 'Female', '5/11/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (75, 'jdomleo22', 'jdomleo22@photobucket.com', 'Jarrad', 'Domleo', 'Male', '10/4/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (76, 'mcaccavella23', 'mcaccavella23@marriott.com', 'Merilyn', 'Caccavella', 'Female', '5/9/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (77, 'ndunsford24', 'ndunsford24@list-manage.com', 'Natalee', 'Dunsford', 'Female', '4/2/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (78, 'rkrout25', 'rkrout25@prlog.org', 'Renelle', 'Krout', 'Female', '7/16/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (79, 'bfrigout26', 'bfrigout26@prlog.org', 'Birdie', 'Frigout', 'Female', '3/16/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (80, 'kchiechio27', 'kchiechio27@tiny.cc', 'Kingsly', 'Chiechio', 'Male', '6/12/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (81, 'rbelford28', 'rbelford28@goo.gl', 'Rickey', 'Belford', 'Genderfluid', '7/14/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (82, 'idomenge29', 'idomenge29@istockphoto.com', 'Irv', 'Domenge', 'Bigender', '3/6/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (83, 'mdrissell2a', 'mdrissell2a@diigo.com', 'Melody', 'Drissell', 'Female', '6/4/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (84, 'vcarver2b', 'vcarver2b@techcrunch.com', 'Verge', 'Carver', 'Male', '2/25/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (85, 'fgehrels2c', 'fgehrels2c@163.com', 'Fabio', 'Gehrels', 'Male', '9/24/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (86, 'pbanfield2d', 'pbanfield2d@cocolog-nifty.com', 'Peggi', 'Banfield', 'Female', '1/2/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (87, 'ygalpin2e', 'ygalpin2e@cnn.com', 'Yvon', 'Galpin', 'Male', '3/5/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (88, 'alohden2f', 'alohden2f@fema.gov', 'Anne', 'Lohden', 'Female', '10/20/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (89, 'dfellgatt2g', 'dfellgatt2g@harvard.edu', 'Darryl', 'Fellgatt', 'Female', '11/18/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (90, 'tbaversor2h', 'tbaversor2h@statcounter.com', 'Thekla', 'Baversor', 'Female', '12/25/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (91, 'rclandillon2i', 'rclandillon2i@latimes.com', 'Rosabelle', 'Clandillon', 'Bigender', '1/14/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (92, 'cesslemont2j', 'cesslemont2j@discuz.net', 'Clare', 'Esslemont', 'Female', '10/1/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (93, 'esprull2k', 'esprull2k@ted.com', 'Elaina', 'Sprull', 'Female', '3/15/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (94, 'bsemiraz2l', 'bsemiraz2l@mysql.com', 'Benjy', 'Semiraz', 'Male', '4/21/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (95, 'gturfs2m', 'gturfs2m@dailymail.co.uk', 'Gianni', 'Turfs', 'Male', '12/26/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (96, 'vgoodread2n', 'vgoodread2n@gnu.org', 'Veronique', 'Goodread', 'Female', '6/11/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (97, 'mchafney2o', 'mchafney2o@un.org', 'Marigold', 'Chafney', 'Female', '4/21/2022');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (98, 'nberzins2p', 'nberzins2p@gnu.org', 'Nikolos', 'Berzins', 'Genderqueer', '6/22/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (99, 'lbaldassi2q', 'lbaldassi2q@taobao.com', 'Lauritz', 'Baldassi', 'Male', '9/6/2021');
insert into MOCK_DATA (id, user_name, Email, first_name, last_name, gender, date_of_birth) values (100, 'ajosefowicz2r', 'ajosefowicz2r@zdnet.com', 'Alley', 'Josefowicz', 'Male', '9/4/2021');
